20 generate a mediadb file for carveme that takes the biolog carbon plates and the carbonless media as input
pnnl-predictive-phenomics/concerto pull request #21
Opened 2024-09-06 04:09 UTC by augeorge

2024-09-11 00:38 UTC, augeorge commented
PR request overview:

this adds functionality in concerto utils that parses a biolog carbon growth data .csv file, and a minimal media data .csv file and creates a media db pandas dataframe that is consistent with carveme formatting. it includes tests for the functions and testing data

1. added functions: parse_carbon_source_growth_file, parse_carbonless_media_file, create_carveme_mediadb_df to concerto/utils/utils.py
2. added test functions: test_parse_carbon_source_growth_file, test_parse_carbonless_media_file, test_create_carveme_mediadb_df to concerto/testing/test_utils.py
3. added testing data: biolog_carbon_curtobacterium1.csv, CarveMeMinimalMediaFile.csv, csc009C-less_media.csv, expected_carbonless_media_df_from_csc009C_less_media.csv, expected_carveme_mediadb_from_biolog_curtobacterium1_and_csc009C_less_media.csv to concerto/testing/data

all tests are now passing in pytest

2024-09-11 00:53 UTC, djinnome requested changes
Looks good. Remove `testing/create_carveme_mediadb_df.py` and I will approve

2024-09-11 00:53 UTC, djinnome commented on concerto/testing/create_carveme_mediadb_df.py
> +    dfbg = pd.read_csv(biolog_carbon_curtobacterium1.csv)
I think line 12 should be:

```python
dfbg = pd.read_csv(fname)
```

2024-09-11 00:53 UTC, djinnome commented on concerto/testing/create_carveme_mediadb_df.py
> +    dfcmin = pd.read_csv(N-less_media.csv)
This function does not have the right inputs or outputs, and dfcmin should be removed.

2024-09-11 00:53 UTC, djinnome commented on concerto/testing/create_carveme_mediadb_df.py
> +    metab_growth_names = metab_growth_names
What is going on here?  Where is `metab_growth_names` defined?

2024-09-11 00:53 UTC, djinnome commented on concerto/testing/create_carveme_mediadb_df.py
This file should be removed.

2024-09-11 03:42 UTC, augeorge commented
> Looks good. Remove `testing/create_carveme_mediadb_df.py` and I will approve

@djinnome removed

2024-09-12 00:04 UTC, djinnome approved these changes
looks good to me!

2024-09-12 00:05 UTC, merged